// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test;

import com.test.Topping;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Topping_Roo_Configurable {
    
    declare @type: Topping: @Configurable;
    
}
